// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_POINTRPY_AIRSIM_TO_ROS_H_
#define FLATBUFFERS_GENERATED_POINTRPY_AIRSIM_TO_ROS_H_

#include "flatbuffers/flatbuffers.h"

namespace airsim_to_ros {

struct PointRPY;

MANUALLY_ALIGNED_STRUCT(8) PointRPY FLATBUFFERS_FINAL_CLASS {
 private:
  double x_;
  double y_;
  double z_;

 public:
  PointRPY() {
    memset(this, 0, sizeof(PointRPY));
  }
  PointRPY(double _x, double _y, double _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  double x() const {
    return flatbuffers::EndianScalar(x_);
  }
  double y() const {
    return flatbuffers::EndianScalar(y_);
  }
  double z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
STRUCT_END(PointRPY, 24);

}  // namespace airsim_to_ros

#endif  // FLATBUFFERS_GENERATED_POINTRPY_AIRSIM_TO_ROS_H_
