version: 2
jobs:
    build:
        docker:
            - image: jonathanschmalhofer/recursivestereo:20180202_alpha_v0
        steps:
            - setup_remote_docker
            - run:
                name: Prepare workspace for checkout
                command: |
                    mkdir -p master_ws/src && cd master_ws/src
            - checkout master_ws/src
            - run:
                name: Build using catkin
                command: |
                    catkin build -c