version: 2
jobs:
    build:
        docker:
            - image: ros:kinetic-perception-xenial
        steps:
            - setup_remote_docker
            - run:
                name: Install missing tools
                command: |
                    apt-get update && \
                    apt-get install -y python-catkin-tools && \
                    apt-get install -y ros-kinetic-desktop-full && \
                    rosdep update && \
                    echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc && \
                    source ~/.bashrc && \
                    source /opt/ros/kinetic/setup.bash && \
                    apt-get install -y python-rosinstall python-rosinstall-generator python-wstool build-essential && \
                    apt-get install -y ros-kinetic-octomap* && \
                    apt-get install -y python-rospkg && \
                    apt-get update && \
                    apt-get install -y qt5-default libeigen3-dev g++ ninja-build cmake clang-format-3.6 ccache libflann-dev qtdeclarative5-dev qtdeclarative5-qtquick2-plugin qml-module-qtquick-{controls,dialogs} libboost-all-dev
            - run:
                name: Prepare workspace for checkout
                command: |
                    mkdir -p ~/master_ws/src && \
                    cd ~/master_ws/src
            - run:
                name: Checkout RecursiveStereoUAV
                command: |
                    cd ~/master_ws/src && \
                    git clone https://github.com/JonathanSchmalhofer/RecursiveStereoUAV.git
            - run:
                name: Download and build wxWidgets 3.1.0 release
                command: |
                    cd ~ && \
                    apt-get install -y wget && \
                    wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.tar.bz2 && \
                    "tar -xf wxWidgets-3.1.0.tar.bz2" && \
                    cd ~/wxWidgets-3.1.0 && \ 
                    mkdir -p ~/wxWidgets-3.1.0/gtk-build && \
                    apt-get install -y libgtk-3-dev build-essential checkinstall && \
                    cd ~/wxWidgets-3.1.0/gtk-build && \
                    ../configure --disable-shared --enable-unicode --with-opengl && \
                    make && \
                    make install
            - run:
                name: Build using catkin
                command: |
                    source /opt/ros/kinetic/setup.bash && \
                    rosdep update && \
                    rosdep install std_msgs && \
                    rosdep install roscpp && \
                    cd ~/master_ws && \
                    catkin build js_airsim_to_ros_node
