version: 2
jobs:
    build:
        docker:
            - image: ros:kinetic-perception-xenial
        steps:
            - setup_remote_docker
            - run:
                name: Install missing tools
                command: |
                    apt-get update && apt-get install -y python-catkin-tools
            - run:
                name: Prepare workspace for checkout
                command: |
                    mkdir -p ~/master_ws/src && cd ~/master_ws/src
            - run:
                name: Checkout RecursiveStereoUAV
                command: |
                    cd ~/master_ws/src && git clone https://github.com/JonathanSchmalhofer/RecursiveStereoUAV.git
            - run:
                name: Build using catkin
                command: |
                    cd ~/master_ws && catkin build -c
