version: 2
jobs:
    build:
        docker:
            - image: ros:kinetic-perception-xenial
        steps:
            - setup_remote_docker
            - run:
                name: Install missing tools
                command: |
                    apt-get update && apt-get install -y python-catkin-tools
            - run:
                name: Prepare, checkout and build
                command: |
                    mkdir -p ~/master_ws/src && \
                    cd ~/master_ws/src && \
                    git clone https://github.com/JonathanSchmalhofer/RecursiveStereoUAV.git && \
                    cd ~/master_sw && \
                    catkin build -c
