version: 2
jobs:
    build:
        docker:
            - image: jonathanschmalhofer/recursivestereo
        steps:
            - setup_remote_docker
            - run:
                name: Prepare workspace for checkout
                command: |
                    mkdir -p ~/master_ws/src && \
                    cd ~/master_ws/src
            - run:
                name: Checkout RecursiveStereoUAV
                command: |
                    cd ~/master_ws/src && \
                    git clone https://github.com/JonathanSchmalhofer/RecursiveStereoUAV.git
            - run:
                name: Build using catkin and run tests
                command: |
                    sudo apt-get install -y python-catkin-tools && \
                    source /opt/ros/kinetic/setup.bash && \
                    rosdep update && \
                    rosdep install std_msgs && \
                    rosdep install roscpp && \
                    cd ~/master_ws && \
                    catkin config --blacklist robojackets_trajectory_planning_node robojackets_3d_trajectory_planning_node js_wxwidget_node && \
                    catkin build -c && \
                    catkin run_tests
