// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TRAJECTORY3DPOINTSTAMPEDROOT_ROS_TO_AIRSIM_H_
#define FLATBUFFERS_GENERATED_TRAJECTORY3DPOINTSTAMPEDROOT_ROS_TO_AIRSIM_H_

#include "flatbuffers/flatbuffers.h"

#include "Point_generated.h"
#include "Pose_generated.h"
#include "Quaternion_generated.h"
#include "time_ros_to_airsim_generated.h"

namespace ros_to_airsim {

struct Trajectory3DPointStamped;

struct Trajectory3DPointStamped FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_TIME = 4,
    VT_POSE = 6
  };
  const time *time() const {
    return GetPointer<const time *>(VT_TIME);
  }
  const Pose *pose() const {
    return GetPointer<const Pose *>(VT_POSE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TIME) &&
           verifier.VerifyTable(time()) &&
           VerifyOffset(verifier, VT_POSE) &&
           verifier.VerifyTable(pose()) &&
           verifier.EndTable();
  }
};

struct Trajectory3DPointStampedBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_time(flatbuffers::Offset<time> time) {
    fbb_.AddOffset(Trajectory3DPointStamped::VT_TIME, time);
  }
  void add_pose(flatbuffers::Offset<Pose> pose) {
    fbb_.AddOffset(Trajectory3DPointStamped::VT_POSE, pose);
  }
  explicit Trajectory3DPointStampedBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  Trajectory3DPointStampedBuilder &operator=(const Trajectory3DPointStampedBuilder &);
  flatbuffers::Offset<Trajectory3DPointStamped> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Trajectory3DPointStamped>(end);
    return o;
  }
};

inline flatbuffers::Offset<Trajectory3DPointStamped> CreateTrajectory3DPointStamped(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<time> time = 0,
    flatbuffers::Offset<Pose> pose = 0) {
  Trajectory3DPointStampedBuilder builder_(_fbb);
  builder_.add_pose(pose);
  builder_.add_time(time);
  return builder_.Finish();
}

inline const ros_to_airsim::Trajectory3DPointStamped *GetTrajectory3DPointStamped(const void *buf) {
  return flatbuffers::GetRoot<ros_to_airsim::Trajectory3DPointStamped>(buf);
}

inline bool VerifyTrajectory3DPointStampedBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ros_to_airsim::Trajectory3DPointStamped>(nullptr);
}

inline void FinishTrajectory3DPointStampedBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ros_to_airsim::Trajectory3DPointStamped> root) {
  fbb.Finish(root);
}

}  // namespace ros_to_airsim

#endif  // FLATBUFFERS_GENERATED_TRAJECTORY3DPOINTSTAMPEDROOT_ROS_TO_AIRSIM_H_
