// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TRAJECTORY3DPOINTSTAMPED_AIRSIM_TO_ROS_H_
#define FLATBUFFERS_GENERATED_TRAJECTORY3DPOINTSTAMPED_AIRSIM_TO_ROS_H_

#include "flatbuffers/flatbuffers.h"

#include "Point_generated.h"
#include "Pose_generated.h"
#include "Quaternion_generated.h"
#include "time_generated.h"

namespace airsim_to_ros {

struct Trajectory3DPointStamped;

MANUALLY_ALIGNED_STRUCT(8) Trajectory3DPointStamped FLATBUFFERS_FINAL_CLASS {
 private:
  time time_;
  Pose pose_;

 public:
  Trajectory3DPointStamped() {
    memset(this, 0, sizeof(Trajectory3DPointStamped));
  }
  Trajectory3DPointStamped(const time &_time, const Pose &_pose)
      : time_(_time),
        pose_(_pose) {
  }
  const time &time() const {
    return time_;
  }
  const Pose &pose() const {
    return pose_;
  }
};
STRUCT_END(Trajectory3DPointStamped, 64);

}  // namespace airsim_to_ros

#endif  // FLATBUFFERS_GENERATED_TRAJECTORY3DPOINTSTAMPED_AIRSIM_TO_ROS_H_
